application:
  subdomain: haven
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://haven:3000/
  injects:
    - id: haven-login-autofill
      when:
        - /users/sign_in
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{ .U.admin_email }}"
            password: "{{ .U.admin_password }}"
            userSelector: "#user_email"
            passwordSelector: "#user_password"
services:
  haven:
    # upstream: ghcr.io/havenweb/haven:latest@sha256:7c902200b37a6963031b1d384140f314dbbc7c42fc6f052d0bb2a36bc2b203b8
    image: registry.lazycat.cloud/czyt/havenweb/haven:5685a96e9a3fafef
    environment:
      - RAILS_ENV=production
      - HAVEN_DB_HOST=haven-pg
      - HAVEN_DB_NAME=haven
      - HAVEN_DB_ROLE=haven
      - HAVEN_DB_PASSWORD={{ stable_secret "haven_db_password" }}
      - HAVEN_USER_EMAIL={{.U.admin_email}}
      - HAVEN_USER_PASS={{.U.admin_password}}
    binds:
      - /lzcapp/var/storage:/app/storage
    depends_on:
      - haven-pg
  haven-pg:
    # upstream: docker.io/library/postgres:17.10-alpine3.24
    image: registry.lazycat.cloud/czyt/library/postgres:e5e91267f148f9b5
    command: >-
      postgres -c max_connections=1000 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c max_wal_size=4GB -c checkpoint_timeout=30min -c wal_level=logical
    environment:
      - POSTGRES_DB=haven
      - POSTGRES_PASSWORD={{ stable_secret "haven_db_password" }}
      - POSTGRES_USER=haven
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U haven -d haven
      start_period: 90s
